apiVersion: v1
kind: Secret
metadata:
  name: nestjs-knex-example-secret
type: Opaque
data:
  DATABASE_URL: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-knex-example-deployment
  labels:
    app: nestjs-knex-example
spec:
  selector:
    matchLabels:
      app: nestjs-knex-example
  template:
    metadata:
      labels:
        app: nestjs-knex-example
    spec:
      containers:
        - name: nestjs-knex-example
          image: nestjs-knex-example
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: nestjs-knex-example-secret
                  key: DATABASE_URL
            
---
apiVersion: v1
kind: Service
metadata:
  name: nestjs-knex-example-service
spec:
  selector:
    app: nestjs-knex-example
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000